# DiscordSRV設定
# 助けが必要ですか？ Discord https://discordsrv.com/discord にご参加ください！

# ここは変更しないでください
ConfigVersion: ${version}

# Bot token: Bot のトークンをここに設定してください。設定方法は、プラグインの導入手順を参照してください。
# このオプションを変更した後、サーバーを再起動する必要があります
BotToken: "BOTTOKEN"

# ゲームからDiscordへのチャンネルリンク
# 構文は Channels: {"Minecraft内のチャンネル名": "Discord内のチャンネルID（数値）", "Minecraft内の別のチャンネル名": "Discord内の別のチャンネルID（数値）"}
#
# DiscordSRV のすべてのメッセージは、そのメッセージの種別に対応したチャンネルが設定されていればそのチャンネルへ、そうでなければ Channels の一つめのチャンネルに送信されます：
# 互換性のあるチャットプラグインを使用する場合、チャンネル名はそのプラグインのものになります（チャットメッセージ用）
#  - TownyChat を使用している場合、デフォルトのチャンネルは通常"global"ではなく"general"と呼ばれます
# プレイヤーのチャット（チャットプラグインを使用していない場合）: global
# サーバーの起動/停止: status
# 実績/進捗: awards
# 死亡: deaths
# 参加通知: join
# 退出通知: leave
# dynmap からのメッセージ: dynmap
# watchdog のメッセージ: watchdog
# /discord broadcast : broadcasts （コマンドで指定されていない場合）
# アカウントのリンク: link
#
# 各チャンネルの組の前半部分は Discord チャンネルの設定ではありません！
# 編集したあとにこの設定を適用するには、「/discord reload」を実行してください
Channels: {"global": "000000000000000000"}

# コンソールチャンネルのID（数値。チャンネル名ではありません)。コンソールチャンネルを無効にする場合は、空のままにしてください。
DiscordConsoleChannelId: "000000000000000000"

# /discord でプレイヤーに表示される招待リンク、およびアカウント連携を強制する際にまだ連携していないプレイヤーに表示される招待リンク
DiscordInviteLink: "https://discord.gg/changethisintheconfig.yml"

# 実験
# これらの機能は完全に最適化されていません。自己責任で使用してください。

# JDBC (MySQL/MariaDB)

Experiment_JdbcAccountLinkBackend: "jdbc:mysql://HOST:PORT/DATABASE?autoReconnect=true&useSSL=false"
Experiment_JdbcTablePrefix: "discordsrv"
Experiment_JdbcUsername: "username"
Experiment_JdbcPassword: "password"

# Webhook の配信
Experiment_WebhookChatMessageDelivery: false
Experiment_WebhookChatMessageUsernameFormat: "%displayname%"
Experiment_WebhookChatMessageFormat: "%message%"
Experiment_WebhookChatMessageUsernameFromDiscord: false
Experiment_WebhookChatMessageAvatarFromDiscord: false
Experiment_WebhookChatMessageUsernameFilters: {}

# 埋め込みと Webhook の画像/アバター URLの形式
# デフォルト値を使用する場合は空白のままにします
# 利用可能なプレースホルダー: {texture} {username} {uuid} {uuid-nodashes} {size}
AvatarUrl: ""

# 書式の再変換
# MinecraftとDiscord間の書式設定（太字、斜体、下線、取り消し線）を変換する
Experiment_MCDiscordReserializer_ToDiscord: false
Experiment_MCDiscordReserializer_ToMinecraft: false
Experiment_MCDiscordReserializer_InBroadcast: false

# This blocks the broadcast event incase you are handling the broadcast with alerts.yml
Experiment_BlockBroadcast: false

# その他
CancelConsoleCommandIfLoggingFailed: true
ForcedLanguage: none
ForceTLSv12: true
NoopHostnameVerifier: false
MaximumAttemptsForSystemDNSBeforeUsingFallbackDNS: 3
TimestampFormat: EEE, d. MMM yyyy HH:mm:ss z
DateFormat: yyyy-MM-dd
# https://docs.discordsrv.com/config/#Timezone
Timezone: default
# MinecraftMentionSound: Discord でメンションされた際に、Minecraft 内のプレイヤーに対して通知音を鳴らすかどうか
MinecraftMentionSound: true

# プラグインのフック
# これらのオプションを変更した場合は、サーバーを再起動する必要があります
#
# DisabledPluginHooks: 無効化されたプラグインフック（通常はプラグインの名前だけ.
# VentureChatBungee: VentureChatフックのBungeeCord機能を有効にします（メッセージはすべてのサーバーから受信され、少なくとも1人のプレイヤーがオンラインである必要があります）
# EnablePresenceInformation: enabled presence information, which is required for some of our PlaceholderAPI placeholders. Keep in mind this requires the "Presence Intent" from the Discord developer portal
# UseModernPaperChatEvent: only use this if you have a chat plugins that SPECIFICALLY utilizes Paper's "AsyncChatEvent"
DisabledPluginHooks: []
VentureChatBungee: false
EnablePresenceInformation: false
UseModernPaperChatEvent: false

# Game Information
# Sets the user status for the bot
# Can be a single, static value, or cycle through multiple different options
# You can preface the status with "playing", "watching", "listening to", or "competing" to set the activity type
# You can set your own custom status by not including the prefixes
#    %online%: number of online players
#    PlaceholderAPI placeholders are supported
#
# DiscordGameStatus: Text to display. Can be a single value e.g. "Minecraft", or multiple values e.g. ["Minecraft", "yourip.changeme.com"]
# DiscordOnlineStatus: Activity status to display. This must be one of the following: ONLINE, DND, IDLE or INVISIBLE
# StatusUpdateRateInMinutes: How frequently to cycle the status
DiscordGameStatus: ["playing Minecraft"]
DiscordOnlineStatus: ONLINE
StatusUpdateRateInMinutes: 2

# チャットチャンネル情報
# チャットチャンネルは、DiscordのテキストチャンネルとMinecraftのゲーム内チャットを紐づけたチャンネルです。
# DiscordのチャットとMinecraftのチャットを、相互に転送することができます。
#
# DiscordChatChannelDiscordToMinecraft: Discordのテキストチャンネルのメッセージをゲーム内チャットに送信するかどうか
# DiscordChatChannelMinecraftToDiscord: ゲーム内チャットのメッセージをDiscordのテキストチャンネルに送信するかどうか
# DiscordChatChannelTruncateLength: DiscordからMinecraftに送信されるメッセージの最大長
# DiscordChatChannelTranslateMentions: @Person for Minecraftのような言い回しをDiscordメッセージに翻訳するかどうか
# DiscordChatChannelAllowedMentions: Minecraft toDiscordメッセージで許可されている言及の種類。 デフォルト値にないタイプは、「role」、「here」、および「everyone」です。
# DiscordChatChannelEmojiBehavior: どのように絵文字をMinecraftに送信するかを指定します。"show"、"name"、"hide"のいずれかです。
# DiscordChatChannelEmoteBehavior: Minecraftへのエモートの送信方法。"name"または "hide"を指定できます。
# DiscordChatChannelPrefixRequiredToProcessMessage: Minecraft から Discord にメッセージを送信するために付けないといけないプレフィックス（例: "!"）。
# DiscordChatChannelPrefixActsAsBlacklist: 上記プレフィックス設定をブラックリストとして動作させるかどうか
# DiscordChatChannelRolesAllowedToUseColorCodesInChat: Discord から Minecraft に送信する際に、カラーコード/フォーマットコードを使用できるロールの一覧
# DiscordChatChannelBroadcastDiscordMessagesToConsole: Discord から送信されたメッセージをコンソールに出力するかどうか
# DiscordChatChannelBlockBots: ボットによる Discord -> MC のメッセージ送信を禁止するかどうか
# DiscordChatChannelBlockWebhooks: Webhook による Discord -> MC のメッセージ送信を禁止するかどうか
# DiscordChatChannelRequireLinkedAccount: Discord -> MC のメッセージ送信に、Discord/MC のアカウント連携を必須とするかどうか
# DiscordChatChannelBlockedIds: MC へのメッセージ送信をブロックする Discord ユーザー（あるいは Bot）のIDリスト
# DiscordChatChannelBlockedRolesAsWhitelist: 上記リストをホワイトリスト（true）として扱う、またはブラックリスト（false）として扱う
# DiscordChatChannelBlockedRolesIds: MC へのメッセージ送信をブロックする Discord ロールのリスト
# DiscordChatChannelRolesSelectionAsWhitelist: 上記リストをホワイトリスト（true）として扱う、またはブラックリスト（false）として扱う
# DiscordChatChannelRolesSelection:すべてのDiscordロールから除外されるロールのリスト
# DiscordChatChannelRoleAliases: ロールのエイリアスのリスト（Minecraft上で表示されるロールの代替名）
#
DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: true
DiscordChatChannelTruncateLength: 256
DiscordChatChannelTranslateMentions: true
DiscordChatChannelAllowedMentions: [user, channel, emote]
DiscordChatChannelEmojiBehavior: "name"
DiscordChatChannelEmoteBehavior: "name"
DiscordChatChannelPrefixRequiredToProcessMessage: ""
DiscordChatChannelPrefixActsAsBlacklist: false
DiscordChatChannelRolesAllowedToUseColorCodesInChat: ["Developer", "Owner", "Admin", "Moderator"]
DiscordChatChannelBroadcastDiscordMessagesToConsole: true
DiscordChatChannelRequireLinkedAccount: false
DiscordChatChannelBlockBots: false
DiscordChatChannelBlockWebhooks: true
DiscordChatChannelBlockedIds: ["000000000000000000", "000000000000000000", "000000000000000000"]
DiscordChatChannelBlockedRolesAsWhitelist: false
DiscordChatChannelBlockedRolesIds: ["000000000000000000", "000000000000000000", "000000000000000000"]
DiscordChatChannelRolesSelectionAsWhitelist: false
DiscordChatChannelRolesSelection: ["Don't show me!", "Misc role"]
DiscordChatChannelRoleAliases: {"Developer": "Dev"}

# コンソールチャンネル情報
# コンソールチャンネルは、DiscordのテキストチャンネルとMinecraftのサーバーコンソールを紐づけたチャンネルです。
# Discordのテキストチャンネルからコンソールにコマンドを送ったり、コンソールの出力内容をDiscordで見たりすることができます。
#
# messages.yml（タイムスタンプの削除を含む）でコンソールメッセージをカスタマイズすることができます。
#
# DiscordConsoleChannelLogRefreshRateInSeconds: コンソールの表示内容を送信する間隔（単位：秒）
# DiscordConsoleChannelUsageLog:
#     %date%:   現在の日付
#              例: 2017-01-01
#    PlaceholderAPI プレースホルダー が使用可能です。
# DiscordConsoleChannelBlacklistActsAsWhitelist: "DiscordConsoleChannelBlacklistedCommands"設定を、ブラックリストの代わりにホワイトリストとして動作させるかどうか
# DiscordConsoleChannelBlacklistedCommands: Discordのユーザーがコンソールにコマンドとして送信できないようにするブラックリスト
# DiscordConsoleChannelBlacklistedCommands: Discordコンソールからの使用を禁止するコマンドのリスト
# DiscordConsoleChannelFilters: コンソールから Discord に送信する際に使用される正規表現フィルター。結果が空になった場合、メッセージは送信されません。
# DiscordConsoleChannelLevels: コンソールチャンネルに表示されるログのレベル
# DiscordConsoleChannelUseCodeBlocks: コンソールをコードブロック囲うかどうか
# DiscordConsoleChannelBlockBots: ボットがコンソールチャンネルでコマンドを送信することを許可するかどうか
#
DiscordConsoleChannelLogRefreshRateInSeconds: 5
DiscordConsoleChannelUsageLog: "Console-%date%.log"
DiscordConsoleChannelBlacklistActsAsWhitelist: false
DiscordConsoleChannelBlacklistedCommands: ["?", "op", "deop", "execute"]
DiscordConsoleChannelFilters: {".*(?i)async chat thread.*": "", ".*There are \\d+ (?:of a max of|out of maximum) \\d+ players online.*": ""}
DiscordConsoleChannelLevels: [info, warn, error]
DiscordConsoleChannelUseCodeBlocks: true
DiscordConsoleChannelBlockBots: true

# チャットチャンネルコマンド実行コマンド
# 登録されたチャットチャンネルから、Prefixを付けてコマンドを書くと、コンソールコマンドを実行させることができます。
# 例えば、"!c kick Notch" のように発言すると、コンソールで "kick Notch" コマンドを実行することができます。
#
# DiscordChatChannelConsoleCommandEnabled: チャットチャンネルからのコンソールコマンドを許可するかどうか
# DiscordChatChannelConsoleCommandNotifyErrors: 権限のないユーザーがコマンドを実行したときに、権限が無いことを通知するかどうか
# DiscordChatChannelConsoleCommandPrefix: コンソールコマンドに使用するPrefix。例: "!c tps"
# DiscordChatChannelConsoleCommandRolesAllowed: チャットチャンネルからサーバーコマンドの実行を許可するロール
# DiscordChatChannelConsoleCommandWhitelist: DiscordChatChannelConsoleCommandPrefixで実行可能なコマンドのリスト
# DiscordChatChannelConsoleCommandWhitelistBypassRoles: コマンドWhitelistに関係なくコマンドを実行することを許可するロールのリスト
# DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: "DiscordChatChannelConsoleCommandWhitelist"設定を、ホワイトリストの代わりにブラックリストとして動作させるかどうか
# DiscordChatChannelConsoleCommandExpiration: 送信されたコマンド出力がボットによって自動的に削除されるまでの時間（秒）。有効期限を無効にするには0に設定します。
# DiscordChatChannelConsoleCommandExpirationDeleteRequest: コマンドを発行した人のメッセージを削除するかどうか
#
DiscordChatChannelConsoleCommandEnabled: true
DiscordChatChannelConsoleCommandNotifyErrors: true
DiscordChatChannelConsoleCommandPrefix: "!c"
DiscordChatChannelConsoleCommandRolesAllowed: ["Owner", "Developer"]
DiscordChatChannelConsoleCommandWhitelist: ["say", "lag", "tps"]
DiscordChatChannelConsoleCommandWhitelistBypassRoles: ["Owner", "Developer"]
DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: false
DiscordChatChannelConsoleCommandExpiration: 0
DiscordChatChannelConsoleCommandExpirationDeleteRequest: true

# チャットチャンネルプレイヤーリストコマンド
# playerlistコマンドの設定内容
#
# DiscordChatChannelListCommandEnabled: コマンドを有効にするかどうか
# DiscordChatChannelListCommandMessage: プレイヤーリストのコマンド
# DiscordChatChannelListCommandExpiration: 送信されたプレイヤーのリストメッセージがボットによって自動的に削除されるまでの時間（秒）。有効期限を無効にするには0に設定します。
# DiscordChatChannelListCommandExpirationDeleteRequest: プレイヤーリストを要求した人のメッセージを削除するかどうか
#
DiscordChatChannelListCommandEnabled: true
DiscordChatChannelListCommandMessage: "playerlist"
DiscordChatChannelListCommandExpiration: 10
DiscordChatChannelListCommandExpirationDeleteRequest: true

# チャットチャンネル ブラックリストのフレーズと正規表現
#
# DiscordChatChannelGameFilters: Discord にメッセージを送信する際に適用される正規表現フィルター。結果が空になった場合、メッセージは送信されません。
# DiscordChatChannelDiscordFilters: Minecraft にメッセージを送信する際に適用される正規表現フィルター。結果が空になった場合、メッセージは送信されません。
#
DiscordChatChannelGameFilters: {}
DiscordChatChannelDiscordFilters: {".*Online players \\(.*": "", ".*\\*\\*No online players\\*\\*.*": ""}

# チャンネルトピック設定
#
# ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: サーバーのシャットダウン時にチャンネルのトピックを変更するかどうか
# ChannelTopicUpdaterRateInMinutes: チャンネルトピックの更新間隔（分）
#
ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: true
ChannelTopicUpdaterRateInMinutes: 10

# チャンネルアップデータ
# ゲーム内プレースホルダーを使用して指定された通りにチャンネル名を変更します
# オプション:
#   ChannelId: 変更するチャンネルのID（必須）
#   Format: チャンネルのフォーマット（必須）。利用可能なプレースホルダー:
#     %playercount%:    現在のプレイヤー数
#     %playermax%:      最大プレイヤー数
#     %date%:           現在の日付と時刻
#     %totalplayers%:   これまでメインのワールドに参加したプレイヤーの総数
#     %uptimemins%:     DiscordSRVが開始されてからの経過分数
#     %uptimehours%:    DiscordSRVが開始されてからの経過時間数
#     %motd%:           サーバーのmotd
#     %serverversion%:  サーバーのバージョン（例：Spigot-1.9）
#     %freememory%:     JVM 内で解放されたメモリ （MB）
#     %usedmemory%:     JVM内で使用済みのメモリ （MB）
#     %totalmemory%:    JVM内での合計メモリ （MB）
#     %maxmemory%:      JVM内での最大メモリ （MB）
#     %freememorygb%:   JVM 内で解放されたメモリ （GB）
#     %usedmemorygb%:   JVM内で使用済みのメモリ （GB）
#     %totalmemorygb%:  JVM内での合計メモリ （GB）
#     %maxmemorygb%:    JVM内での最大メモリ （GB）
#     %tps%:            サーバーの平均TPS
#     PlaceholderAPIプレースホルダーも使用可能です。
#   ShutdownFormat: サーバーがシャットダウンした際のフォーマット。利用可能なプレースホルダー:
#     %time% または %date%:  現在の日付と時刻
#     %serverversion%:      サーバーのバージョン
#     %totalplayers%:       これまでメインのワールドに参加したプレイヤーの総数
#     %timestamp%:          現在の unix タイムスタンプ
#   UpdateInterval: チャンネル名の更新間隔（分）（レート制限のため、10 が最小値）
ChannelUpdater:
  - ChannelId: "0000000000000000"
    Format: "%playercount% 人がオンライン"
    ShutdownFormat: "サーバーはオフラインです"
    UpdateInterval: 10
  - ChannelId: "0000000000000000"
    Format: "現在のTPS: %tps%"
    ShutdownFormat: "サーバーはオフラインです"
    UpdateInterval: 10

# Discord 定型文応答
# これらは、定型文を返信するための設定です。
# この設定を独自のものに変更することが推奨されるでしょう。
#
# 書き方は、  {"トリガー": "応答", "トリガー": "応答", ...}
# 定型文の応答を必要としない場合は、{} を設定してください。
# PlaceholderAPIプレースホルダが使用可能です。
#
DiscordCannedResponses: {"!ip": "yourserveripchange.me", "!site": "http://yoursiteurl.net"}

# Minecraft から Discord へのアカウント連携
# これらは、MinecraftアカウントとDiscordアカウントを連携する機能に関する設定オプションです
#
# MinecraftDiscordAccountLinkedConsoleCommands: アカウントが連携された際に実行されるコマンド。使用可能なプレースホルダは以下を参照してください。
# MinecraftDiscordAccountUnlinkedConsoleCommands: アカウントのリンクが解除された際に実行されるコマンド。使用可能なプレースホルダは以下を参照してください。
# %minecraftplayername%: Minecraftのプレイヤー名
#                         例: Notch
# %minecraftuuid%:       プレイヤーのUUID
#                         例: you know what a uuid looks like
# %discordid%:           リンクされる・された Discord アカウントのID
#                         例: 12345678901234567890
# %discordname%:         リンクされる・された Discord アカウント名
#                         例: Notch
#
# MinecraftDiscordAccountLinkedRoleNameToAddUserTo: Discordユーザーがアカウントをリンクするときに追加するDiscordロール名またはID
# MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: 新しいコードをボットに送信して新しいコードとのリンクを解除して再リンクすることを許可する
# MinecraftDiscordAccountLinkedUsePM: PMを使用してアカウントをリンクする
# MinecraftDiscordAccountLinkedMessageDeleteSeconds: テキストチャンネルでリンクをした際のメッセージを削除するまでの時間（秒）。0 を設定すると削除されません。
#
MinecraftDiscordAccountLinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountUnlinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountLinkedRoleNameToAddUserTo: "Linked"
MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: false
MinecraftDiscordAccountLinkedUsePM: true
MinecraftDiscordAccountLinkedMessageDeleteSeconds: 0

# Server watchdog
#
# watchdog は、最新のゲームチックとその時刻を常に監視します。
# ゲームチックの間隔がが閾値（秒）を超えると、Discordメッセージがトリガーされます
# サーバーが重くなっていることを通知するために使用してください
#
# ServerWatchdogEnabled: watchdog を有効にするかどうか
# ServerWatchdogTimeout: watchdog が動作するまでの待機時間（Spigotのクラッシュ検出では、60秒が使用されています）
#                        この設定の最小値は10秒です。
# ServerWatchdogMessageCount: ServerWatchdogMessage が送信される回数。何が起きているかを **本当に** 確かめたい場合には有用です。
#
ServerWatchdogEnabled: true
ServerWatchdogTimeout: 60
ServerWatchdogMessageCount: 3

# HTTP proxy used for connecting to the Discord API
# Leave this alone if you don't understand what it does
ProxyHost: "example.com"
ProxyPort: 1234
ProxyUser: "USERNAME"
ProxyPassword: "PASSWORD"

# デバッグ情報
# 問題を特定しようとする際以外はこの設定を使用しないでください。
#
# 利用可能なデバッグカテゴリ:
# MINECRAFT_TO_DISCORD  - Minecraft からのメッセージ
# DISCORD_TO_MINECRAFT  - Discord からのメッセージ
# GROUP_SYNC            - グループの同期
# PRESENCE              - Bot のゲームステータスと状態
# VOICE                 - 音声モジュール（voice.yml を参照）
# REQUIRE_LINK          - モジュールを追加するために必要なリンク（linking.yml を参照）
# NICKNAME_SYNC         - ニックネームの同期
# ALERTS                - アラート (alerts.yml を参照)
# WATCHDOG              - サーバー の watchdog
# BAN_SYNCHRONIZATION   - BAN 同期
# LP_CONTEXTS           - LuckPermのコンテキスト
# ACCOUNT_LINKING       - Discord/Minecraft のアカウント連携
#
# UNCATEGORIZED         - 上記のいずれにも該当しないもの
# ALL                   - 上記のすべてのカテゴリ（UNCATEGORIZEDを含む）
#
# JDA                   - JDA のデバッグメッセージ
# JDA_REST_ACTIONS      - JDA の残りのアクションのデバッグ用
# CALLSTACKS            - DiscordSRV デバッグ呼び出しのスタックトレース
#
# 例: "Debug: [GROUP_SYNC, PRESENCE]"
#
Debug: []
