# Configuration DiscordSRV
# Besoin d'aide? Rejoignez notre Discord, https://discordsrv.com/discord

# Merci de ne pas toucher ceci
ConfigVersion: ${project.version}

# Bot token; Vous ne savez pas ce que c'est ? Regardez la vidéo sur la page du plugin
BotToken: "BOTTOKEN"

# Liens de chaîne du jeu vers Discord
# la syntaxe est Channels: {"nom de chaîne dans le jeu de Minecraft": "ID de chaîne numérique de Discord", "autre nom de chaîne de jeu de Minecraft": "autre ID de chaîne numérique de Discord"}
#
# Tous les messages de DiscordSRV iront sur le premier canal à moins qu'il n'y ait un canal pour ce type de messages défini:
# lors de l'utilisation d'un plugin de chat compatible, le nom du canal sera celui de ce plugin (pour les messages de chat)
#  - Si vous utilisez TownyChat, le canal par défaut est généralement appelé "general" au lieu de "global"
# pour les messages de chat des joueurs (lorsque vous n'utilisez pas de plugin de chat): global
# pour les messages de réussite / d'avancement: awards
# pour les messages de mort: deaths
# pour rejoindre les messages: join
# pour laisser des messages: leave
# pour les messages dynmap: dynmap
# pour les messages de surveillance: watchdog
# pour / discord broadcast: broadcasts (sauf si spécifié dans la commande)
#
# La première partie des paires de canaux n'est pas le nom du canal Discord!
Channels: {"global": "000000000000000000"}

# ID du channel console (PAS DE NOM), ne rien remplir si vous souhaitez désactiver cette fonction
DiscordConsoleChannelId: "000000000000000000"

# Lien d'invitation affiché aux joueurs lors de l'utilisation de /discord et sur le message affiché aux joueurs non liés lorsque la liaison est appliquée
DiscordInviteLink: "discord.gg/changethisintheconfig.yml"

# Option de debug, ne touchez pas sauf si vous en avez besoin
#
# Niveau de debug: 0 = pas de debug, 1 = debug, 2 = debug avec log
#
DebugLevel: 0
DebugJDA: false
DebugJDARestActions: false
CancelConsoleCommandIfLoggingFailed: true
RespectChatPlugins: true
ForcedLanguage: none
Experiment_JdbcAccountLinkBackend: "jdbc:mysql://HOST:PORT/DATABASE?autoReconnect=true&useSSL=false"
Experiment_JdbcTablePrefix: "discordsrv"
Experiment_JdbcUsername: "username"
Experiment_JdbcPassword: "password"
Experiment_WebhookChatMessageDelivery: false
Experiment_WebhookChatMessageUsernameFormat: "%displayname%"
Experiment_WebhookChatMessageUsernameFromDiscord: false
Experiment_EmbedAvatarUrl: https://minotar.net/helm/{uuid-nodashes}/{size}
#Experiment_EmbedAvatarUrl: https://minotar.net/helm/{username}
Experiment_WebhookChatMessageAvatarFromDiscord: false
Experiment_MCDiscordReserializer_ToDiscord: false
Experiment_MCDiscordReserializer_ToMinecraft: false
Experiment_MCDiscordReserializer_InBroadcast: false
Experiment_Automatic_Color_Translations: false
PrintGuildsAndChannels: true
ForceTLSv12: true
NoopHostnameVerifier: false
ParseEmojisToNames: true
MaximumAttemptsForSystemDNSBeforeUsingFallbackDNS: 3

# Crochets de plugin
#
# DisabledPluginHooks: hooks de plugin qui ne seront pas utilisés (généralement juste le nom du plugin)
# VentureChatBungee: active la fonctionnalité BungeeCord du hook VentureChat (les messages sont reçus de chaque serveur, au moins 1 joueur doit être en ligne)
# EnablePresenceInformation: enabled presence information, which is required for some of our PlaceholderAPI placeholders. Keep in mind this requires the "Presence Intent" from the Discord developer portal
DisabledPluginHooks: []
VentureChatBungee: false
EnablePresenceInformation: false

# Game Information
# Sets the "Playing: ______" indicator for the bot.
# Can be a single, static value, or cycle through multiple different options
# You can preface the status with "playing", "watching", or "listening to" to set the activity type
# PlaceholderAPI placeholders are supported
#
# DiscordGameStatus: Text to display. Can be a single value e.g. "Minecraft", or multiple values e.g. ["Minecraft", "yourip.changeme.com"]
# StatusUpdaterRateInMinutes: How frequently to cycle the status
DiscordGameStatus: "Minecraft"
StatusUpdateRateInMinutes: 2

# Channel de tchat
# Le channel de tchat est le salon ou tous les messages en jeu seront envoyés au Discord et tous les messages Discord envoyés au jeu
#
# DiscordChatChannelDiscordToMinecraft: envoie des messages Discord sur Minecraft ou non
# DiscordChatChannelMinecraftToDiscord: envoie des messages Minecraft sur le Discord ou non
# DiscordChatChannelTruncateLength: la longueur maximale des messages Discord à envoyer sur Minecraft
# DiscordChatChannelTranslateMentions: si oui ou non pour traduire les mentions comme @Person pour les messages de Minecraft à Discord
# DiscordChatChannelAllowedMentions: types de mentions autorisées dans les messages Minecraft to Discord; les types manquants dans la valeur par défaut sont "role", "here" et "everyone"
# DiscordChatChannelPrefixRequiredToProcessMessage: la caractère requis qui précède un message pour l'envoyer depuis Minecraft sur Discord (Exemple : "!")
# DiscordChatChannelRolesAllowedToUseColorCodesInChat: liste des rôles autorisés à envoyer des messages de couleur depuis Discord sur Minecraft
# DiscordChatChannelBroadcastDiscordMessagesToConsole: envoie des messages Discord sur la console ou non
# DiscordChatChannelRequireLinkedAccount: les joueurs doivent-ils avoir un compte lié avant d'envoyer des messages depuis Discord sur Minecraft
# DiscordChatChannelBlockBots: si les bots doivent ou non être bloqués de Discord -> MC chat
# DiscordChatChannelBlockedIds: ID des utilisateurs Discord dont les messages ne seront pas envoyés
# DiscordChatChannelColorTranslations: couleurs hexadécimales répresentant les couleurs Minecraft
# DiscordChatChannelRolesSelectionAsWhitelist: si la liste suivante doit être traitée comme une liste blanche (true) ou une liste noire (false)
# DiscordChatChannelRolesSelection: la liste des rôles devant être filtrés de tous les rôles d'un utilisateur
#
DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: true
DiscordChatChannelTruncateLength: 256
DiscordChatChannelTranslateMentions: true
DiscordChatChannelAllowedMentions: [user, channel, emote]
DiscordChatChannelPrefixRequiredToProcessMessage: ""
DiscordChatChannelRolesAllowedToUseColorCodesInChat: ["Developer", "Owner", "Admin", "Moderator"]
DiscordChatChannelBroadcastDiscordMessagesToConsole: true
DiscordChatChannelRequireLinkedAccount: false
DiscordChatChannelBlockBots: false
DiscordChatChannelBlockedIds: ["000000000000000000", "000000000000000000", "000000000000000000"]
DiscordChatChannelColorTranslations: {
  "99AAB5": "&f",
  "1ABC9C": "&a",
  "2ECC71": "&a",
  "3498DB": "&3",
  "9B59B6": "&5",
  "E91E63": "&d",
  "F1C40F": "&e",
  "E67E22": "&6",
  "E74C3C": "&c",
  "95A5A6": "&7",
  "607D8B": "&8",
  "11806A": "&2",
  "1F8B4C": "&2",
  "206694": "&1",
  "71368A": "&5",
  "AD1457": "&d",
  "C27C0E": "&6",
  "A84300": "&6",
  "992D22": "&4",
  "979C9F": "&7",
  "546E7A": "&8"
}
DiscordChatChannelRolesSelectionAsWhitelist: false
DiscordChatChannelRolesSelection: ["Don't show me!", "Misc role"]

# Channel console
# Le channel console est un channel qui reçoit des messages de la console.
# Les messages envoyés eux sont envoyés comme des commandes à la console
#
# DiscordConsoleChannelLogRefreshRateInSeconds: nombre de secondes entre les rafraichissements de message
# DiscordConsoleChannelUsageLog:
#    %date%:  date actuelle
#              exemple: 2017-01-01
#    Les espaces réservés de PlaceholderAPI sont pris en charge
# DiscordConsoleChannelBlacklistActsAsWhitelist: définit si la liste est une liste blanche ou une liste noire
# DiscordConsoleChannelBlacklistedCommands: phrases/commandes que les joueurs ne peuvent pas envoyer depuis le channel
# DiscordConsoleChannelFilters: filtres regex à appliquer aux lignes de console envoyées à Discord, si le résultat est vide, le message ne sera pas envoyé du tout
# DiscordConsoleChannelLevels: niveaux à envoyer à la console par l'intermédiaire de l'appender
# DiscordConsoleChannelAllowPluginUpload: devrait télécharger des plugins sur le canal de la console les ajouter automatiquement au serveur
#
DiscordConsoleChannelLogRefreshRateInSeconds: 5
DiscordConsoleChannelUsageLog: "Console-%date%.log"
DiscordConsoleChannelBlacklistActsAsWhitelist: false
DiscordConsoleChannelBlacklistedCommands: ["?", "op", "deop", "execute"]
DiscordConsoleChannelFilters: {".*(?i)async chat thread.*": "", ".*There are \\d+ of a max of \\d+ players online.*": ""}
DiscordConsoleChannelLevels: [info, warn, error]
DiscordConsoleChannelAllowPluginUpload: false

# Channel de tchat Commande d'exécution
# Ces options gèrent la fonction d'écrire "!c kick Notch", ou n'importe quel préfixe pour envoyer une commande,
# en tant que console, depuis un channel enregistré.
#
# DiscordChatChannelConsoleCommandEnabled: autorisation ou non d'envoyer des commandes depuis le channel console
# DiscordChatChannelConsoleCommandNotifyErrors: envoie d'un message ou non d'interdiction si un utilisateur tente de taper une commande sans permission
# DiscordChatChannelConsoleCommandPrefix: prefixe à utiliser pour envoyer une commande. Exemple : "!c tps"
# DiscordChatChannelConsoleCommandRolesAllowed: rôles autorisés à envoyer des commandes depuis le channel console
# DiscordChatChannelConsoleCommandWhitelist: liste des commandes autorisées avec DiscordChatChannelConsoleCommandPrefix
# DiscordChatChannelConsoleCommandWhitelistBypassRoles: liste des rôles qui contourne la liste blanche
# DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: la liste des commandes doit agir comme une liste blanche ou une liste noire
# DiscordChatChannelConsoleCommandExpiration: temps en secondes avant qu'une commande soit retiré après avoir été envoyée.
# DiscordChatChannelConsoleCommandExpirationDeleteRequest: suppression automatique ou non d'une commande après avoir été envoyée.
#
DiscordChatChannelConsoleCommandEnabled: true
DiscordChatChannelConsoleCommandNotifyErrors: true
DiscordChatChannelConsoleCommandPrefix: "!c"
DiscordChatChannelConsoleCommandRolesAllowed: ["Developer", "Owner"]
DiscordChatChannelConsoleCommandWhitelist: ["say", "lag", "tps"]
DiscordChatChannelConsoleCommandWhitelistBypassRoles: ["Owner", "Developer"]
DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: false
DiscordChatChannelConsoleCommandExpiration: 0
DiscordChatChannelConsoleCommandExpirationDeleteRequest: true

# Channel de tchat liste des commandes joueur
# All the config stuff for the player list command
#
# DiscordChatChannelListCommandEnabled: la commande est-elle activée ou non ?
# DiscordChatChannelListCommandMessage: commande à taper si les joueurs veulent voir la liste de joueurs en ligne
# DiscordChatChannelListCommandExpiration: temps en seconde avant la suppression de la liste des joueurs
# DiscordChatChannelListCommandExpirationDeleteRequest: suppression automatique de la liste des joueurs après envoie ou non
#
DiscordChatChannelListCommandEnabled: true
DiscordChatChannelListCommandMessage: "playerlist"
DiscordChatChannelListCommandExpiration: 10
DiscordChatChannelListCommandExpirationDeleteRequest: true

# Channel de tchat Phrases interdites
#
# DiscordChatChannelGameFilters: filtres regex à appliquer aux messages de chat envoyés à Discord, si le résultat est vide, le message ne sera pas envoyé du tout
# DiscordChatChannelDiscordFilters: filtres regex à appliquer aux messages de discussion envoyés à Minecraft, si le résultat est vide, le message ne sera pas envoyé du tout
#
DiscordChatChannelGameFilters: {}
DiscordChatChannelDiscordFilters: {".*Online players\\(.*": "", ".*\\*\\*No online players\\*\\*.*": ""}

# Mse à jour des informations du canal
#
# ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: le message d'informations du canal doit être changé lors de l'arrêt du serveur ou non
# ChannelTopicUpdaterRateInMinutes: temps en minutes entre les mises à jour des informations sur les chaînes
#
ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: true
ChannelTopicUpdaterRateInMinutes: 10

# Réponses automatiques Discord
# Ces phrases (commandes en quelque sorte) envoient une réponse si elles sont tapées
# Vous pouvez modifier ces dernières pour mettre les votres
#
# Syntaxe {"Commande": "Réponse", "Commande": "Réponse", ...}
# Si vous ne voulez aucune réponse laissez vide
# PlaceholderAPI : les placeholders sont compatibles
#
DiscordCannedResponses: {"!ip": "yourserveripchange.me", "!site": "http://yoursiteurl.net"}

# Liaison d'un compte Minecraft sur Discord
# Configuration de la liaison d'un compte Minecraft sur Discord
#
# MinecraftDiscordAccountLinkedConsoleCommands: commandes à envoyer lors d'une liaison, les placeholders sont compatibles
# %minecraftplayername%: Nom Minecraft du joueur
#                         Exemple: Notch
# %minecraftuuid%:       UUID du joueur
#                         Exemple: vous savez à quoi ressemble un UUID
# %discordid%:           ID compte Discord
#                         Exemple: 12345678901234567890
# %discordname%:         Nom Discord du joueur
#                         Exemple: Notch
#
# MinecraftDiscordAccountLinkedRoleNameToAddUserTo: rôle à mettre au joueur qui vient de lié son compte
# MinecraftDiscordAccountLinkedSetDiscordNicknameAsInGameName: le nom discord du joueur doit-il être modifié par son nom Minecraft ?
# MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: permet d'envoyer un nouveau code au bot pour dissocier et relier le nouveau code
#
MinecraftDiscordAccountLinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountUnlinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountLinkedRoleNameToAddUserTo: "Linked"
MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: false

# Surveilleur de serveur
#
# Surveille constamment la dernière fois que votre serveur a effectué une tick de jeu
# Si le temps écoulé depuis la dernière coche dépasse l'intervalle défini en secondes, les messages Discord sont envoyés
#
# ServerWatchdogEnabled: surveillement ou non
# ServerWatchdogTimeout: temps en seconde avant que le surveillement envoie un message (La détection de crash de spigot utilise 60)
#                        la valeur minimum est 10
# ServerWatchdogMessageCount: nombre de fois que le message est envoyé
#
ServerWatchdogEnabled: true
ServerWatchdogTimeout: 30
ServerWatchdogMessageCount: 3
