# Niet veranderen graag. (Do not change!)
ConfigVersion: ${project.version}

# Bot token; Weet je niet wat dit is? Kijk de video op de plugin pagina voor instructies.
BotToken: "BOTTOKEN"

# Kanaal link van je server naar Discord.
# Volgorde is Channels: {"in spel kanaal naam": "Kanaal ID van Discord", "Ander in spel kanaal naam": "Ander kanaal ID van Discord"}
# Het eerste kanaal dat is opgegeven in deze configuratie is het 'Hoofd' kanaal, dit wordt gebruikt om de joins/quits/deaths/achievements/etc weer te geven.
#
Channels: {"global": "000000000000000000"}

# Console kanaal ID (NIET de naam!). Leeg laten om deze funtie uit te schakelen.
DiscordConsoleChannelId: "000000000000000000"

# Debug opties, Niet aanraken tenzij nodig!
#
# DebugLevel: 0 = geen debug, 1 = debug, 2 = debug met 'stack traces'
#
DebugLevel: 0
DebugJDA: false
CancelConsoleCommandIfLoggingFailed: true
RespectChatPlugins: true
ForcedLanguage: none
Experiment_JdbcAccountLinkBackend: "jdbc:mysql://HOST:PORT/DATABASE?useSSL=false"
Experiment_JdbcTablePrefix: "discordsrv"
Experiment_JdbcUsername: "username"
Experiment_JdbcPassword: "password"
Experiment_WebhookChatMessageDelivery: false
Experiment_MCDiscordReserializer: false
WebhookAvatarsAre3d: false
PrintGuildsAndChannels: true
ForceTLSv12: true
SponsorPebbleHost: true

# Uitgeschakelde plugin hooks.
# Niet aanraken, tenzij nodig.
#
DisabledPluginHooks: []

# Spel informatie, hiermee verander je de "Speelt: _____" functie van je bot in Discord, verander naar "" om het uit te schakelen.
DiscordGameStatus: "Minecraft"

# Chat kanaal informatie.
# Het chat kanaal is de text channel op Discord waar alle in-spel berichten komen.
# Alle berichten die in de text channel op Discord worden gestuurd worden ook in-spel gestuurd.
#
# DiscordChatChannelDiscordToMinecraft: Of de berichten in het chat kanaal op Discord ook naar de server gestuurt moeten worden.
# DiscordChatChannelMinecraftToDiscord: Of de berichten in de in-game chat ook naar het chat kanaal op Discord gestuurt moeten worden.
# DiscordChatChannelTruncateLength: De maximale lengte van berichten op Discord die naar minecraft moeten worden gestuurd.
# DiscordChatChannelTranslateMentions: Om al dan niet vermeldingen zoals @Person voor Minecraft naar Discord-berichten te vertalen
# DiscordChatChannelPrefix: Het teken dat voor een bericht moet zitten iets van Minecraft naar Discord the sturen (Bijvoorbeeld "!" of "+")
# DiscordChatChannelRolesAllowedToUseColorCodesInChat: Lijst van 'roles' die kleuren codes mogen gebruiken in Discord naar Minecraft chat.
# DiscordChatChannelBroadcastDiscordMessagesToConsole: Of de berichten wel of niet ook nar de console moeten worden gestuurd.
# DiscordChatChannelRequireLinkedAccount: Of spelers hun Discord account moeten hebben verbonden aan hun Minecraft account voordat ze iets kunnen sturen in Discord.
# DiscordChatChannelBlockBots: Of bot(s) wel of niet berichten kunnen sturen in Minecraft chat.
# DiscordChatChannelBlockedIds: IDs van Discord gebruikters (of bots) die geen berichten naar de Minectraft chat mogen sturen.
# DiscordChatChannelColorTranslations: Kleur codes van Discord vergeleken met de kleur codes van Minecraft
# DiscordChatChannelRolesSelectionAsWhitelist: als de volgende lijst moet worden behandeld als een witte lijst (waar) of een zwarte lijst (false)
# DiscordChatChannelRolesSelection: lijst met 'roles' die moeten worden gefilterd uit alle rollen van een gebruiker
#
DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: true
DiscordChatChannelTruncateLength: 256
DiscordChatChannelTranslateMentions: true
DiscordChatChannelPrefix: ""
DiscordChatChannelRolesAllowedToUseColorCodesInChat: ["Developer", "Eigenaarr", "Beheerder", "Moderator"]
DiscordChatChannelBroadcastDiscordMessagesToConsole: true
DiscordChatChannelRequireLinkedAccount: false
DiscordChatChannelBlockBots: false
DiscordChatChannelBlockedIds: ["000000000000000000", "000000000000000000", "000000000000000000"]
DiscordChatChannelColorTranslations: {
  "99AAB5": "&f",
  "1ABC9C": "&a",
  "2ECC71": "&a",
  "3498DB": "&3",
  "9B59B6": "&5",
  "E91E63": "&d",
  "F1C40F": "&e",
  "E67E22": "&6",
  "E74C3C": "&c",
  "95A5A6": "&7",
  "607D8B": "&8",
  "11806A": "&2",
  "1F8B4C": "&2",
  "206694": "&1",
  "71368A": "&5",
  "AD1457": "&d",
  "C27C0E": "&6",
  "A84300": "&6",
  "992D22": "&4",
  "979C9F": "&7",
  "546E7A": "&8"
}
DiscordChatChannelRolesSelectionAsWhitelist: false
DiscordChatChannelRolesSelection: ["Don't show me!", "Misc role"]

# Console kanaal informatie
# Het console kanaal is het text kanaal dat berichten ontvangt die ook in de console te zien zijn.
# Commands die in het Discord console kanaal worden gestuurd worden ook naar de server gestuurd.
#
# Je kan alle berichten en alle 'timestamps' aanpassen in "messages.yml".
#
# DiscordConsoleChannelLogRefreshRateInSeconds: Tijd in secondes tussen het versturen van berichten van de console.
# DiscordConsoleChannelUsageLog: De naam van het bestand waar alle commmands staan die door gebruikers in de Discord console zijn verstuurd.
# DiscordConsoleChannelBlacklistActsAsWhitelist: Of de 'blacklisted' commands als 'Whitelisted' commands moeten worden gezien.
# DiscordConsoleChannelBlacklistedCommands: Deze commands kunnen niet worden uitgevoerd zolang "DiscordConsoleChannelBlacklistActsAsWhitelis:" "false" is.
# DiscordConsoleChannelDoNotSendPhrasesActsAsWhitelist: Of de "do not send" lijst als 'whitelist' moet worden gezien in plaats van 'blacklist'.
# DiscordConsoleChannelDoNotSendPhrases: Deze commands kunnen niet worden uitgevoerd zolang "DiscordConsoleChannelDoNotSendPhrasesActsAsWhitelist:" "false" is.
# DiscordConsoleChannelRegexFilter: Of de 'regex filter' moet gebruikt op 'lines' die worden verstuurd naar Discord.
# DiscordConsoleChannelRegexReplacement: Met wat het 'regex filter' de woorden zal vervangen als een woord is gevonden dat in het 'regex filter' staat
# DiscordConsoleChannelLevels: Levels berichten om te versturen naar Discord console channel via appender
#
DiscordConsoleChannelLogRefreshRateInSeconds: 5
DiscordConsoleChannelUsageLog: "DiscordConsole.log"
DiscordConsoleChannelBlacklistActsAsWhitelist: false
DiscordConsoleChannelBlacklistedCommands: ["?", "op", "deop"]
DiscordConsoleChannelDoNotSendPhrasesActsAsWhitelist: false
DiscordConsoleChannelDoNotSendPhrases: ["async chat thread"]
DiscordConsoleChannelRegexFilter: ""
DiscordConsoleChannelRegexReplacement: ""
DiscordConsoleChannelLevels: [info, warn, error]

# Discord Chat kanaal command, uitvoering command
# Deze opties zijn voor de mogelijkheid om "!c kick Notch", (of een andere prefix)to run a command,
# Zo kan je commands als 'console' uitvoeren terwijl je ze in Discord text channel in voert.
#
# DiscordChatChannelConsoleCommandEnabled: Of er console commands in het chat kanaal gebruikt mogen worden.
# DiscordChatChannelConsoleCommandNotifyErrors: Of een speler gewaarschuwd moet worden als hij geen rechten heeft voor een bepaald command.
# DiscordChatChannelConsoleCommandPrefix: De prefix voor console commands in Discord chat kanaal (Bijvoorbeeld "!c tps")
# DiscordChatChannelConsoleCommandRolesAllowed: De lijst van 'roles' die console commands mogen gebruiken in Discord chat kanaal.
# DiscordChatChannelConsoleCommandWhitelist: Lijst van commands die kunnen worden gebruikt.
# DiscordChatChannelConsoleCommandWhitelistBypassRoles: Lijst van mensen waarvoor de 'whitelist' niet geldt.
# DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: Moet de 'whitelist' als 'blacklist' gezien worden?
# DiscordChatChannelConsoleCommandExpiration: Tijd in seconden voordat een command automatisch verwijderd moet worden. Verander naar "0" om het uit te schakelen.
# DiscordChatChannelConsoleCommandExpirationDeleteRequest: Of het bericht van de persoon die als eerst de command uivoerde ook verwijderd moet worden.
#
DiscordChatChannelConsoleCommandEnabled: true
DiscordChatChannelConsoleCommandNotifyErrors: true
DiscordChatChannelConsoleCommandPrefix: "!c"
DiscordChatChannelConsoleCommandRolesAllowed: ["Developer", "Eigenaar"]
DiscordChatChannelConsoleCommandWhitelist: ["say", "lag", "tps"]
DiscordChatChannelConsoleCommandWhitelistBypassRoles: ["Eigenaar", "Developer"]
DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: false
DiscordChatChannelConsoleCommandExpiration: 0
DiscordChatChannelConsoleCommandExpirationDeleteRequest: true

# Chat kanaal speler lijst commands
# Alle opties voor de spelers lijst.
#
# DiscordChatChannelListCommandEnabled: Het aan of uit zetten van de spelers lijst
# DiscordChatChannelListCommandMessage: Het commands voor de spelers lijstthe command people can type to get the player list
# DiscordChatChannelListCommandExpiration: Tijd in seconden voordat een command automatisch verwijderd moet worden. Verander naar "0" om het uit te schakelen.
# DiscordChatChannelListCommandExpirationDeleteRequest: Of het bericht van de persoon die als eerst de command uivoerde ook verwijderd moet worden.
#
DiscordChatChannelListCommandEnabled: true
DiscordChatChannelListCommandMessage: "playerlist"
DiscordChatChannelListCommandExpiration: 10
DiscordChatChannelListCommandExpirationDeleteRequest: true

# Text kanaal 'blacklisted' woorden en filters.
#
# DiscordChatChannelBlockedPhrases: Woorden waarvan als ze in een zin zitten, het gehele bericht niet verstuurd wordt.
# DiscordChatChannelCutPhrases: Woorden in Minecraft chat, als die een van de vernoemde woorden bevat wordt het woord uit de zin gelaten.
# DiscordChatChannelRegex: 'regex' om de chat naar minecraft mee te filteren.
# DiscordChatChannelRegexReplacement: replacement for above option
#
DiscordChatChannelBlockedPhrases: ["Online spelers (", "**Geen spelers online**"]
DiscordChatChannelCutPhrases: ["@everyone"]
DiscordChatChannelRegex: ""
DiscordChatChannelRegexReplacement: ""

# Kanaal topic update instellingen
#
# ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: Of het kanaal 'topic' moet worden aangepast als de server stopt.
# ChannelTopicUpdaterRateInMinutes: Tijd in minuten tussen updates van de kanaal 'topic' met nieuwe informatie.
#
ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: true
ChannelTopicUpdaterRateInMinutes: 5

# Discord canned antwoorden
# Dit zijn de de commands voor Discord waar een vast antwoord op is.
# Je kan deze instellingen volledig aanpassen en bijvoorbeeld je eigen IP invullen.
#
# Volgorde is {"TRIGGER": "RESPONSE", "TRIGGER": "RESPONSE", ...}
# Als je geen commands in Discord wil verander het dan naar {}
# PlaceholderAPI placeholders zijn ondersteund.
#
DiscordCannedResponses: {"!ip": "serverip.me", "!site": "http://jesiteulr.nl"}

# Minecraft naar Discord account koppelen.
# Dit zijn de opties die bepalen hoe het koppelen tussen Minecraft en Discord werkt.
#
# MinecraftDiscordAccountLinkedConsoleCommands: Commands om uit te voeren als een account gekoppeld is, kijk onder voor placeholders.
# MinecraftDiscordAccountUnlinkedConsoleCommands: Commands om uit te voeren als een account ontkoppeld is, kijk onder voor placeholders.
# %minecraftplayername%: Speler's Minecraft username
#                         Bijvoorbeeld: Notch
# %minecraftuuid%:       Speler's uuid
#                         Bijvoorbeeld: you know what a uuid looks like
# %discordid%:           Gekoppeld Discord account ID
#                         Bijvoorbeeld: 12345678901234567890
# %discordname%:         Gekoppeld Discord account naam
#                         Bijvoorbeeld: Notch
#
# MinecraftDiscordAccountLinkedRoleToAddUserTo: De naam van de discord role als ze hun account gekoppeld hebben.
# MinecraftDiscordAccountLinkedSetDiscordNicknameAsInGameName: Of de Discord naam veranderd moet worden naar de in-game naam.
# MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: hiermee kan een nieuwe code naar de bot worden verzonden om te ontkoppelen en opnieuw te koppelen aan de nieuwe code
#
MinecraftDiscordAccountLinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountUnlinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountLinkedRoleNameToAddUserTo: "Linked"
MinecraftDiscordAccountLinkedSetDiscordNicknameAsInGameName: false
MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: false

# Minecraft groep -> Discord 'role' synchronisatie
#
# GroupRoleSynchronizationRoleIdsToSync: Dit zijn de Discord 'role' IDs die hiervoor gesynchroniseerd moeten zijn.
#                                        Als een 'role' ID hier niet is dan heeft de permission (discordsrv.sync.[role id]) geen zin.
#                                         Om je Discord guild's role IDs te krijgen, doe "/discord debug" en kijk in de eerst sectie.
# GroupRoleSynchronizationCycleTime: amount of minutes between repeatedly triggering synchronization for all online players
# GroupRoleSynchronizationRemoveRolesOnUnlink: Of de 'role' weggehaald moet worden als de speler zijn account ontkoppeld.
#
GroupRoleSynchronizationRoleIdsToSync: ["000000000000000000", "000000000000000000", "000000000000000000"]
GroupRoleSynchronizationCycleTime: 5
GroupRoleSynchronizationRemoveRolesOnUnlink: true

# Server watchdog
#
# De watchdog kijkt de hele tijd naar de laatste keer dat de server een 'game tick' heeft gedaan.
# Als de tijd boven een bepaald punt komt (in secondes), Kan Discord een bericht sturen.
#
# ServerWatchdogEnabled: Of whatchdog aan staat of niet.
# ServerWatchdogTimeout: Tijd in secondes voordat whatchdog iets doet (Spigot's crash detection gebruikt 60 voor dit)
#                        Het minimun getal is 10
# ServerWatchdogMessageCount: Het aantal keer dat ServerWatchdogMessage wordt verstuurd. Handig als je *echt* wil weten als er iets aan de hand is.
#
ServerWatchdogEnabled: true
ServerWatchdogTimeout: 30
ServerWatchdogMessageCount: 3

# Ban synchronisatie
# Als een speler gebanned wordt op de server en zijn/haar account is gekoppeld aan Discord dan kan de speler ook daar gebanned worden. Kan ook andersom.
#
# BanSynchronizationDiscordToMinecraft: Of mensen gebanned moeten worden als ze op Discord worden gebanned. (Discord -> Minecraft)
# BanSynchronizationDiscordToMinecraftReason: De ban reden die gebruikt wordt voor het bannen van mensen op de Minecraft server.
# BanSynchronizationMinecraftToDiscord: Of mensen gebanned moeten worden als ze op Minecraft worden gebanned. (Minecraft -> Discord)
#
BanSynchronizationDiscordToMinecraft: false
BanSynchronizationDiscordToMinecraftReason: "&cJe bent gebanned van de server omdat je bent gebanned op onze Discord server."
BanSynchronizationMinecraftToDiscord: false
