blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Get help
    url: https://discord.discordsrv.com
    about: "If you need help configuring the plugin or have a question please join our Discord server and do so in our #support channel."
  - name: ðŸ“š Search for documentation
    url: https://github.com/DiscordSRV/DiscordSRV/wiki
    about: In our wiki you can find explanations and examples on how to configure our plugin properly.